# Generated by Django 6.0.2 on 2026-03-07 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('facilities', '0001_initial'),
        ('resources', '0002_alter_resource_options'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, help_text='The specific user assigned to approve this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_for_approval', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='booking_ref',
            field=models.CharField(blank=True, help_text='Auto-generated unique reference e.g. BK-20260001', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='booking_type',
            field=models.CharField(choices=[('academic_workshop', 'Academic Workshop'), ('seminar', 'Seminar'), ('guest_lecture', 'Guest Lecture'), ('student_event', 'Student Event'), ('inter_college_event', 'Inter-College Event'), ('admin_meeting', 'Admin Meeting'), ('external_conference', 'External Conference'), ('sports_booking', 'Sports Booking'), ('research_access_request', 'Research Access Request'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='calendar_event_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores event metadata for calendar display'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='expected_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='requires_approval',
            field=models.BooleanField(default=True, help_text='Set automatically by apply_policy() at submission time'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='sub_unit',
            field=models.ForeignKey(blank=True, help_text='For per-unit bookings (e.g. one PC in a computer lab)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='resources.subresourceunit'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='facilities.room'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='tenants.tenant'),
        ),
        migrations.CreateModel(
            name='BookingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded to Next Approver')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='bookings.bookingrequest')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True, help_text='URL to uploaded file in storage')),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bookings.bookingrequest')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingConflictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(blank=True, help_text='room / resource / sub_unit', max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('attempted_start', models.DateTimeField()),
                ('attempted_end', models.DateTimeField()),
                ('conflict_reason', models.TextField(blank=True)),
                ('attempted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflict_attempts', to=settings.AUTH_USER_MODEL)),
                ('conflicting_with', models.ForeignKey(help_text='The existing approved booking that caused the conflict', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_conflicts', to='bookings.bookingrequest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingParticipantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, help_text='e.g. Speaker, Faculty Guide, Student', max_length=100)),
                ('is_external', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='bookings.bookingrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingPolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('role_based', 'Role-Based Rule'), ('booking_type_based', 'Booking Type Rule'), ('time_based', 'Time/After-Hours Rule'), ('resource_based', 'Resource Category Rule')], max_length=50)),
                ('applies_to_roles', models.JSONField(blank=True, default=list, help_text="List of role names this rule applies to, e.g. ['student','external_user']")),
                ('applies_to_booking_types', models.JSONField(blank=True, default=list, help_text="List of booking_type values, e.g. ['seminar','auditorium']")),
                ('after_hours_only', models.BooleanField(default=False, help_text='If True, rule only applies for bookings outside 8am–6pm on weekdays')),
                ('requires_approval', models.BooleanField(default=True)),
                ('approver_role', models.CharField(default='facility_manager', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_policies', to='tenants.tenant')),
            ],
            options={
                'ordering': ['rule_type'],
            },
        ),
        migrations.CreateModel(
            name='RecurringBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('recurrence_days', models.JSONField(blank=True, default=list, help_text='Days of week for weekly recurrence. 0=Monday, 6=Sunday.')),
                ('series_start', models.DateField()),
                ('series_end', models.DateField()),
                ('total_occurrences', models.PositiveIntegerField(default=0)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_requests', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_bookings', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='recurring_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='bookings.recurringbooking'),
        ),
    ]
