# Generated by Django 4.2.11 on 2026-03-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('resources', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(blank=True, max_length=200)),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.PositiveIntegerField(default=1)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.department')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
