# Generated by Django 4.2.11 on 2026-03-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('resources', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('internal', 'Internal Assessment'), ('mid', 'Mid Semester'), ('end', 'End Semester'), ('practical', 'Practical'), ('viva', 'Viva Voce')], max_length=20)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.PositiveIntegerField(default=1)),
                ('invigilators', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.department')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='resources.resource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
    ]
