# Generated by Django 4.2.11 on 2026-03-07 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_batch_section_alter_academicyear_options_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='academics.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='academics.course')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='academics.section')),
            ],
        ),
        migrations.CreateModel(
            name='ExamHallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_capacity', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_hall_allocations', to='resources.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plans', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_plans', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exam_plans', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plans', to='academics.semester')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_plans', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamPublishLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('publish', 'Published'), ('unpublish', 'Unpublished'), ('archive', 'Archived')], max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_actions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_logs', to='exams.examplan')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('forenoon', 'Forenoon (FN)'), ('afternoon', 'Afternoon (AN)')], default='forenoon', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.examplan')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('plan', 'date', 'session_type')},
            },
        ),
        migrations.CreateModel(
            name='InvigilatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chief_invigilator', models.BooleanField(default=False)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilators', to='exams.examhallallocation')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_invigilations', to='academics.facultyprofile')),
            ],
            options={
                'unique_together': {('allocation', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_roll_number', models.CharField(max_length=50)),
                ('seat_number', models.PositiveIntegerField()),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='exams.examhallallocation')),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='exams.examcourseassignment')),
            ],
            options={
                'ordering': ['allocation', 'seat_number'],
                'unique_together': {('allocation', 'seat_number')},
            },
        ),
        migrations.DeleteModel(
            name='ExamSchedule',
        ),
        migrations.AddField(
            model_name='examhallallocation',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_allocations', to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='examcourseassignment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='exams.examsession'),
        ),
        migrations.AlterUniqueTogether(
            name='examhallallocation',
            unique_together={('session', 'resource')},
        ),
        migrations.AlterUniqueTogether(
            name='examcourseassignment',
            unique_together={('session', 'course', 'batch', 'section')},
        ),
    ]
