# Generated by Django 4.2.11 on 2026-03-07 05:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('institution_type', models.CharField(choices=[('engineering', 'Engineering'), ('arts_science', 'Arts & Science'), ('management', 'Management'), ('research', 'Research'), ('university', 'University')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
