# Generated by Django 4.2.11 on 2026-03-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('booking_summary', 'Booking Summary'), ('resource_utilization', 'Resource Utilization'), ('department_usage', 'Department Usage')], max_length=50)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
