# Generated by Django 6.0.2 on 2026-03-07 08:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_total', models.IntegerField(default=1)),
                ('quantity_available', models.IntegerField(default=1)),
                ('unit_type', models.CharField(default='Unit', help_text='e.g. System, Seat, Kit', max_length=50)),
                ('bookable_as_whole', models.BooleanField(default=True)),
                ('bookable_per_unit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('active', 'Active/In Use'), ('maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned'), ('broken', 'Broken/Repair Needed')], default='available', max_length=20)),
                ('maintenance_status', models.CharField(choices=[('good', 'Good'), ('pending', 'Pending Maintenance'), ('overdue', 'Overdue'), ('critical', 'Critical Issue')], default='good', max_length=20)),
                ('requires_approval', models.BooleanField(default=False)),
                ('restricted_roles', models.JSONField(blank=True, default=list, help_text='List of roles allowed to book this resource')),
                ('notes', models.TextField(blank=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_resources', to='facilities.room')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_resources', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Checkup'), ('repair', 'Repair'), ('calibration', 'Calibration'), ('upgrade', 'Software/Hardware Upgrade')], max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('performed_by', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('work_description', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('last_calibration_date', models.DateField(blank=True, null=True)),
                ('next_calibration_due', models.DateField(blank=True, null=True)),
                ('safety_instructions', models.TextField(blank=True)),
                ('is_high_precision', models.BooleanField(default=False)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_details', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_categories', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_tags', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_resources', to='resources.resourcetag'),
        ),
        migrations.CreateModel(
            name='SubResourceUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_identifier', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('active', 'Active/In Use'), ('maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned'), ('broken', 'Broken/Repair Needed')], default='available', max_length=20)),
                ('is_bookable', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_units', to='resources.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UtilizationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('usage_type', models.CharField(blank=True, max_length=100)),
                ('log_data', models.JSONField(blank=True, default=dict)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilization_logs', to='resources.resource')),
                ('sub_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.subresourceunit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('tenant', 'resource_code')},
        ),
        migrations.CreateModel(
            name='RoomResourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_mappings', to='resources.resource')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_mappings', to='facilities.room')),
            ],
            options={
                'unique_together': {('room', 'resource')},
            },
        ),
    ]
